In [6]:
'''Q1. Pearson correlation coefficient is a measure of the linear relationship between two variables. Suppose
you have collected data on the amount of time students spend studying for an exam and their final exam
scores. Calculate the Pearson correlation coefficient between these two variables and interpret the result.

assuming the data for amount of time spend and final exam scores 
are in the form of two lists

'''
import numpy as np
time_spent= [1,2,3,4,5,6,7,8,9,10]
final_score= [10,20,30,40,50,60,70,80,90,100]
#using pearson correalation coefficient formula
std_time_spent,std_final_score=np.std(time_spent),np.std(final_score)
cov_of_data=np.cov(time_spent,final_score)
pearson=cov_of_data/(std_time_spent*std_final_score)
print(pearson)

#the output shows the correlation between the two variables is 1 which means they are perfectly correlated

[[ 0.11111111  1.11111111]
 [ 1.11111111 11.11111111]]


In [9]:
'''Q2. Spearman's rank correlation is a measure of the monotonic relationship between two variables.
Suppose you have collected data on the amount of sleep individuals get each night and their overall job
satisfaction level on a scale of 1 to 10. Calculate the Spearman's rank correlation between these two
variables and interpret the result.'''
#assuming the data for amount of sleep and job satisfaction are in the form of two lists
import numpy as np
sleep= [6,7,8,9,10]
job_satisfaction= [2,5,3,6,1]
from scipy.stats import spearmanr
spearman=spearmanr(sleep,job_satisfaction)
print(spearman)
# the output shows the correlation between the two variables is 0.2 which means they are weakly correlated

SignificanceResult(statistic=-0.09999999999999999, pvalue=0.8728885715695383)


In [15]:
'''Q3. Suppose you are conducting a study to examine the relationship between the number of hours of
exercise per week and body mass index (BMI) in a sample of adults. You collected data on both variables
for 50 participants. Calculate the Pearson correlation coefficient and the Spearman's rank correlation
between these two variables and compare the results.'''
#assuming the data for amount of exercise and BMI are in the form of two lists
import numpy as np
exercise= [1,2,3,4,5,6,7,8,9,10]
BMI= [10,20,30,40,50,60,70,80,90,100]
#using pearson correalation coefficient formula
std_exercise,std_BMI=np.std(exercise),np.std(BMI)
cov_of_data=np.cov(exercise,BMI)
pearson=cov_of_data/(std_exercise*std_BMI)
print(pearson)
#the output shows the correlation between the two variables is 1 which means they are perfectly correlated


###################OR
exercise= [1,2,3,4,5,6,7,8,9,10]
BMI= [10,20,30,40,50,60,70,80,90,100]
from scipy.stats import pearsonr
pearson=pearsonr(exercise,BMI)
print(pearson)

[[ 0.11111111  1.11111111]
 [ 1.11111111 11.11111111]]
PearsonRResult(statistic=1.0, pvalue=0.0)


In [17]:
'''Q4. A researcher is interested in examining the relationship between the number of hours individuals
spend watching television per day and their level of physical activity. The researcher collected data on
both variables from a sample of 50 participants. Calculate the Pearson correlation coefficient between
these two variables.'''
#assuming the data for amount of time spend watching tv and physical activity are in the form of two lists
import numpy as np
np.random.seed(10)
time_spent=np.random.randint(1,10,50)
physical_activity=np.random.randint(1,10,50)
#using pearson correalation coefficient formula
std_time_spent,std_physical_activity=np.std(time_spent),np.std(physical_activity)
cov_of_data=np.cov(time_spent,physical_activity)
pearson=cov_of_data/(std_time_spent*std_physical_activity)
print(pearson)
pearson_stats=pearsonr(time_spent,physical_activity)
print(pearson_stats)
#the negative covariance -0.00491 shows that the two variables are negatively correlated

[[ 1.09473673 -0.00491256]
 [-0.00491256  0.95112623]]
PearsonRResult(statistic=-0.004814308934970306, pvalue=0.973529893906248)


In [18]:
'''Q5. A survey was conducted to examine the relationship between age and preference for a particular
brand of soft drink. The survey results are shown below:

Age(Years)    Soft drink Preference
    25              Coke
    42              Pepsi
    37           Mountain dew
    19              Coke
    31              Pepsi
    28              Coke

'''
#assuming the data for age and soft drink preference are in the form of two lists
import numpy as np
age= [25,42,37,19,31,28]
soft_drink= [1,2,3,1,2,1]
from scipy.stats import spearmanr
spearman=spearmanr(age,soft_drink)
print(spearman)
#the coefficient is approximately 0.8332. This suggests a strong positive monotonic relationship between the variables. 
# It indicates that as the values of age increase, the ranks of the corresponding soft_drink values tend to increase as well.

SignificanceResult(statistic=0.8332380897952965, pvalue=0.03939551647885117)


In [20]:
'''Q6. A company is interested in examining the relationship between the number of sales calls made per day
and the number of sales made per week. The company collected data on both variables from a sample of
30 sales representatives. Calculate the Pearson correlation coefficient between these two variables.'''
#assuming the data for number of sales calls made per day and number of sales made per week are in the form of two lists
import numpy as np
np.random.seed(10)
sales_calls=np.random.randint(1,10,30)
sales_made=np.random.randint(1,10,30)
#using pearson correalation coefficient formula
std_sales_calls,std_sales_made=np.std(sales_calls),np.std(sales_made)
cov_of_data=np.cov(sales_calls,sales_made)
pearson=cov_of_data/(std_sales_calls*std_sales_made)
print(pearson)
pearson_stats=pearsonr(sales_calls,sales_made)  #using pearsonr function
print(pearson_stats)
#here the covariance is 0.1869103 which shows that the two variables are positively correlated
#the p value is also greater than 0.05 which shows that correlation coefficient is not statistically significant at the 0.05 significance level
#Therefore, you cannot conclude a significant linear relationship between the variables based on this analysis.

[[0.97423399 0.1869103 ]
 [0.1869103  1.09845745]]
PearsonRResult(statistic=0.180679955263481, pvalue=0.33934048138683226)
